version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: puckel/docker-airflow:1.10.9
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: airflow
      POSTGRES_HOST: postgres
      EXECUTOR: Local
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    networks:
      - airflow_network

  etl:
    image: python:3.9-slim
    container_name: etl_container
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: python scripts/load.py

volumes:
  postgres_data:

networks:
  airflow_network:
    driver: bridge
